apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-fltt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-fltt
    app.kubernetes.io/part-of: appstudio
  name: devfile-sample-python-basic-fltt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-fltt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-fltt
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-rtkh-tenant/appstudio/devfile-sample-python-basic-fltt@sha256:65f73b891a2eb6a96ff3b26208d6bef93256e8220fb6f6e0133513182e6704b2
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
