apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-tu32
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-tu32
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-tu32
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-tu32
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-tu32
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-rtkh-tenant/appstudio/dc-metro-map-tu32@sha256:32390e83b20dcc6aeb47595483082106198b0d2f4ee4a127d19c20d89724d655
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
